### ISSUE TITLE
Issue with bert-base-uncased label_map file

### ISSUE THREAD

**Issue by davidcoallier** [bhavitvyamalik/DialogTag#1]
## Problem

In the [label_map.txt](https://www.dropbox.com/sh/ajlwp36obho2cbe/AADHTY4_PhSOAQzveCJIna4Va?preview=label_map.txt) file for the `bert-base-uncased` model, it appears that the line for **Reject** contains an extraneous `|` character which is throwing a `ValueError` when attempting to unpack it. 

## Reproduce

```python
from dialog_tag import DialogTag

model = DialogTag('bert-base-uncased')
output = model.predict_tag('What kind of question is this?')
```

This should throw the `ValueError` exception:

```
  File "/venv/lib/python3.8/site-packages/dialog_tag/DialogTag.py", line 59, in predict_tag
    logits_class, class_expanded = self.__classhelper()
  File "/venv/lib/python3.8/site-packages/dialog_tag/DialogTag.py", line 43, in __classhelper
    logits_class, class_expanded = mapping_object.helper()
  File "/venv/lib/python3.8/site-packages/dialog_tag/label_mapping.py", line 20, in helper
    act,label = row.strip().split('|')
ValueError: too many values to unpack (expected 2)
```

## Potential Solution

Since the mapping file isn't in Github I can't send you a PR but the following line: 

```
Reject|ar|344
```

Should become:

```
Reject|ar
```

**Comment by bhavitvyamalik** [comment]
Thanks for reporting the issue @davidcoallier. As a fix I've updated the `label_map.txt` on the Dropbox. Now you'll get updated label mapping file once you clear the cache and re-download it. Thanks again!
